### ISSUE TITLE
user has type "any" in sanitizeUser

### ISSUE THREAD

**Issue by DoctorDerek** [alan2207/bulletproof-react#11]
https://github.com/alan2207/bulletproof-react/blob/6f7d873bf6200b8fe6cceea7ceec5cede7856a25/src/test/server/utils.ts#L25

Hey, I don't understand the typing going on here well enough to fix this, but it doesn't help reliability here.

Isn't anything with `any` type an ESLint error anyway? I usually set it as such.

**Comment by thebergamo** [comment]
I guess once it defines how an user looks like it would be too dependent. On your own code you should specialize the user and of course also omit proper fields in this case.

Those are the most common that usually you want to sanitize as `password` is pretty obvious and `iat` is related mainly with JWT. 

So, use it just as an example and extend it on your need.

**Comment by alan2207** [comment]
Exactly what @thebergamo said. This function shouldn't care about the shape of the user, it should just remove data you don't want to expose to the API. It doesn't throw errors because explicit `any` type is allowed, you should just use it only when necessary.
