### ISSUE TITLE
Typescript error in form.tsx

### ISSUE THREAD

**Issue by thanhtutzaw** [alan2207/bulletproof-react#112]
### Typescript error in form.tsx
![Screenshot (137)](https://user-images.githubusercontent.com/71011043/211142196-b56876bf-2a7d-4280-a062-290be9a37a09.png)

**Comment by lokeshgaria** [comment]
@thanhtutzaw i've fixed this issue

**Comment by thanhtutzaw** [comment]
> @thanhtutzaw i've fixed this issue 
> 

How do you solved it ? I just update and re install npm and it works magically. I think it is version problem. I don't remember how I solved exactly but It worked.
