### ISSUE TITLE
Can I get new updated package.json because I got a lot of error to run locally this "bulletproof"

### ISSUE THREAD

**Issue by thanhtutzaw** [alan2207/bulletproof-react#119]
### Can I get new updated package.json because I got a lot of error to run locally this "bulletproof"

**Comment by Olegato** [comment]
The same problem

**Comment by ThePiyushAggarwal** [comment]
Steps I use to run the project.
- Switch to node version 16. Precisely 16.19.0 works for me.
- Run command `yarn` at the root of the repo to install the dependencies for the project.
- Run command `yarn start` at the root of the repo to run the project.
- If you get an error related to LF and CRLF line endings in windows, I don't have exact solution for that. You need to search for that. I implemented a quick fix to run the project which is modify .eslintrc.js file to remove lines 34, 45, 71. Which removed prettier plugin and linebreak complaints.

**Comment by brucejing** [comment]
I resolved it by using npm instead of yarn.
1. uninstall node
2. install node 16.20.2
3. npm install
4. npm run start
