### ISSUE TITLE
Failed to load page after registering a user on standalone 

### ISSUE THREAD

**Issue by vchan14** [alan2207/bulletproof-react#126]
Running with: 
> Node - v14.21.3
> Yarn - 1.22.19

After registering the first user, I will get an error message below. I have tried to delete the local storage `msw-db` and it goes back to the start page. Then when registering the first user again, it will throw the same error. 

Errors from console:

> Uncaught Error: Absolute route path "/discussions/*" nested under path "/app" is not valid. An absolute child route path must start with the combined path of all its parent routes.

> 
> The above error occurred in the <AppRoutes> component:
> 
> AppRoutes@http://localhost:3000/static/js/main.chunk.js:8872:73
> Router@http://localhost:3000/static/js/vendors~main.chunk.js:181740:7
> BrowserRouter@http://localhost:3000/static/js/vendors~main.chunk.js:179993:7
> AuthProvider@http://localhost:3000/static/js/vendors~main.chunk.js:174178:20
> QueryClientProvider@http://localhost:3000/static/js/vendors~main.chunk.js:178980:16
> r@http://localhost:3000/static/js/vendors~main.chunk.js:171728:21
> ErrorBoundary@http://localhost:3000/static/js/vendors~main.chunk.js:169377:37
> Suspense
> AppProvider@http://localhost:3000/static/js/main.chunk.js:8587:7
> App

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/30560223/235570901-1419a99b-d874-4037-a916-a095821ef9ac.png">

**Comment by thaihoangminh** [comment]
Hi @vchan14,  Please remove the slash from your path. 
You should change `path="/discussions/*"` to `path="discussions/*"`
