### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by Fekry-Ahmed** [alan2207/bulletproof-react#127]
Hello there, I am facing a problem with starting the server and previewing the app

I did these steps
1- clone the repo 
2- run npm install
3- npm start

And this error is shown in the console 

----------------------------
PS D:\Liked Projects\bulletproof-react> npm start  
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> bulletproof-react@0.1.0 start
> craco start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  D:\Liked Projects\bulletproof-react\node_modules\babel-loader (version: 8.3.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if D:\Liked Projects\bulletproof-react\node_modules\babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

**Comment by jay08111** [comment]
Have you tried with yarn? write "yarn" after cloned the project then "yarn start".
It works in my case.

**Comment by Fekry-Ahmed** [comment]
It worked! Thank you!

**Comment by jacksonpradolima** [comment]
@Fekry-Ahmed great! Can you close this issue?
