### ISSUE TITLE
Network Error when sign up or login？

### ISSUE THREAD

**Issue by 826625219** [alan2207/bulletproof-react#143]
![image](https://github.com/alan2207/bulletproof-react/assets/72744302/4dba213d-2ae5-4907-9232-ca3f985739ba)

**Comment by nicolasdanelon** [comment]
you have to copy the `.env.example` in the root folder but the domain is down, so it won't work.

if you want to create mocked endpoints I suggest to define the `REACT_APP_API_URL` variable in your environment.

**Comment by 826625219** [comment]
thanks



---Original---
From: "Nicolas ***@***.***&gt;
Date: Sat, Dec 30, 2023 20:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alan2207/bulletproof-react] Network Error when sign up or login？ (Issue #143)




 
you have to copy the .env.example in the root folder but the domain is down, so it won't work.
 
if you want to create mocked endpoints I suggest to define the REACT_APP_API_URL variable in your environment.
