### ISSUE TITLE
Ejecting the webpack

### ISSUE THREAD

**Issue by krishnaUIDev** [alan2207/bulletproof-react#15]
Hello, 

are you guys planning to eject webpack? Now this boilerplate webpack is depend on react-scripts.

Thanks.

**Comment by LissetteIbnz** [comment]
I think you can use craco tool if you need handle the webpack config 

More info: https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#webpack-api

**Comment by alan2207** [comment]
Hi. First of all, this repo is not a boilerplate, it should only serve as an example for a good react project architecture.

As @LissetteIbnz said, craco allows you to extend your webpack configuration without ejecting it if you really want that.
