### ISSUE TITLE
[minor]: Typo in ~/README.md

### ISSUE THREAD

**Issue by marktoh** [alan2207/bulletproof-react#156]
## Description
Going through the README.md, I found that there was a full stop missing for one of the sentences.

| Preview  | Fix |
| ------------- | ------------- |
| <img width="878" alt="Screenshot 2024-05-16 at 9 27 59 PM" src="https://github.com/alan2207/bulletproof-react/assets/25725495/17111b73-4780-495d-828b-ca9c38f479f4"> | <img width="256" alt="Screenshot 2024-05-16 at 9 27 34 PM" src="https://github.com/alan2207/bulletproof-react/assets/25725495/809628b2-2679-48d7-98bf-fe778973ba65">  |

I tried making a PR for this but ran into some permissions issue.

```
 git push --set-upstream origin fix-root-readme-typo
remote: Permission to alan2207/bulletproof-react.git denied to marktoh.
fatal: unable to access 'https://github.com/alan2207/bulletproof-react.git/': The requested URL returned error: 403
```

It's a small one but hope it helps!

**Comment by seantcanavan** [comment]
you have to create a fork of the original repo and push your changes to the fork then open a PR from fork to here. the permission error you're seeing is likely because you're trying to push directly against this repo which you don't have permission to.

**Comment by marktoh** [comment]
@seantcanavan Thank you. I created a PR here, https://github.com/alan2207/bulletproof-react/pull/158. Please let me know if that works.
