### ISSUE TITLE
a lot of packages used are deprecated

### ISSUE THREAD

**Issue by ahmednawaz10p** [alan2207/bulletproof-react#16]
![image](https://user-images.githubusercontent.com/75250585/127762922-a2dd3c4c-b661-4eee-a192-dcf1486d5819.png)

i cloned the repo and ran `npm i`. it appears the project has alot of deprecated/old dependencies. I am using node 14.

**Comment by Ahmiimec** [comment]
Noticed the same issue , was using Node 10 and had to update to latest Node...

**Comment by Manubi** [comment]
I guess this repo tries to give you a general idea to do things. Most of the ideas behind the decisions don't change with another version of a package. I wouldn't recommend to clone the repo, I would rather see it as a place for inspiration.

**Comment by alan2207** [comment]
This is a great point made by @Manubi. The repo should be used to give inspiration on how to build react applications. 

On the other hand, it is nice to be able to clone the repo and start the app and play around with the code. 

@ahmednawaz10p  have you tried to install it with Yarn? I haven't noticed any warnings by using it.
