### ISSUE TITLE
Some links are Not found 

### ISSUE THREAD

**Issue by yuvarajsai** [alan2207/bulletproof-react#166]
1. In [App errors](https://github.com/alan2207/bulletproof-react/blob/master/docs/error-handling.md#in-app-errors), the link specified at Error boundary Example code is Not found. Seems like the file it is pointing to might have been deleted.

![image](https://github.com/alan2207/bulletproof-react/assets/63961211/b00cd048-be81-438a-9ca0-711c8fc0671b)

2. In [Code splitting] (https://github.com/alan2207/bulletproof-react/blob/master/docs/performance.md#code-splitting), Code splitting example code link is not found.
https://github.com/alan2207/bulletproof-react/blob/master/src/routes/index.tsx

![image](https://github.com/alan2207/bulletproof-react/assets/63961211/998ae961-db90-4a93-97fc-271a719e4dbf)

On clicking on the link:
![image](https://github.com/alan2207/bulletproof-react/assets/63961211/351707f6-99b6-4465-bab9-8e48a832edbd)

**Comment by alan2207** [comment]
Fixed in https://github.com/alan2207/bulletproof-react/pull/169
