### ISSUE TITLE
Clean installation fails on "yarn install" errors

### ISSUE THREAD

**Issue by craigmcc** [alan2207/bulletproof-react#17]
Following the instructions in [https://github.com/alan2207/bulletproof-react/blob/master/docs/application-overview.md](url) I got the following errors in the console log (Mac OSX):

```
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
warning Resolution field "babel-loader@8.1.0" is incompatible with requested version "babel-loader@^8.2.2"
warning Resolution field "babel-loader@8.1.0" is incompatible with requested version "babel-loader@^8.2.2"
warning Resolution field "babel-loader@8.1.0" is incompatible with requested version "babel-loader@^8.2.2"
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "/Users/craigmcc/Library/Caches/Yarn/v6/npm-upper-case-1.1.3-f6b4501c2ec4cdd26ba78be7222961de77621598-integrity/node_modules/upper-case/.yarn-metadata.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/Users/craigmcc/Git.Examples/bulletproof-react/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
The referenced `yarn-error.log` file is attached below:
[yarn-error.log](https://github.com/alan2207/bulletproof-react/files/6919997/yarn-error.log)

**Comment by alan2207** [comment]
Hi @craigmcc , which yarn version are you using? I am using yarn as well, and the installation completes without any issues.

**Comment by craigmcc** [comment]
I am using yarn 1.22.10 -- usually use npm so no idea if this is current or not.  But the complaints in the logs are all about dependency version incompatibilities, so I don't expect that would be an issue.

**Comment by alan2207** [comment]
Have you tried to install with npm? Does it still fail?

**Comment by craigmcc** [comment]
It fails with npm as well.  Messages are slightly different, but there's "dependency of children" issues somewhere.

**Comment by alan2207** [comment]
I inspected where the `upper-case` package is being used and it is used in `plop` which is not crucial in order to run the application. I would suggest you uninstall `plop` and try again. I know it is not an ideal solution, but if you want to run the app, it might work. I am also wondering if anyone else experienced this issue?

**Comment by alan2207** [comment]
That is great, enjoy! :)
