### ISSUE TITLE
Documentation discrepancy 

### ISSUE THREAD

**Issue by waterbuffalo5** [alan2207/bulletproof-react#181]
Hi, I'm new to react, so I'm unsure if this is intentional, but the documentation lists the file names as _app.tsx_ and _app-provider_, but actual file names are _index.tsx_ and _main-provider.tsx_

Thanks

```
src
|
+-- app               # application layer containing:
|   |
|   +-- routes        # application routes / can also be called pages
    +-- app.tsx       # main application component
    +-- app-provider  # application provider that wraps the entire application with global providers
```

**Comment by alan2207** [comment]
Hey there! Naming in this context does not matter that much, it should just give you some ideas where to place what, you name it whatever makes the most sense for you and your team.
