### ISSUE TITLE
[QUESTION] - Barrel file performance

### ISSUE THREAD

**Issue by Zac-Evans** [alan2207/bulletproof-react#188]
Hey there - I'm using the bulletproof-react repo as a reference while structuring my project. It has been super helpful! I have a question though about your usage of barrel files in the components folder. 

https://vitejs.dev/guide/performance#avoid-barrel-files

The Vite documentation recommends avoiding barrel files for performance reasons, so I was wondering if you knew about or had taken into consideration. I'd imagine the impact isn't significant in the sample app, but I'm wondering how it would affect large-scale apps. Thanks!

**Comment by alan2207** [comment]
Hey @Zac-Evans , yes, this recommendation has been changed if you see the latest docs: https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md

**Comment by Zac-Evans** [comment]
Okay great, I figured I might be missing something. Thanks!
