### ISSUE TITLE
SUGGESTION: Terminal Application

### ISSUE THREAD

**Issue by maliksenpai** [alan2207/bulletproof-react#201]
I liked this project very much, but an idea came to my mind. While creating a project like vitejs, we can make adjustments to the project via the terminal, we can something like that. For example, we can define .env file via terminal. Then we can develop it further and add features such as adding .scss to all pages. Also anyone can use this project with npm rather than git clone. For example:

npm create bulletproof-react@latest

If you find it suitable, I can do it. 

@alan2207

**Comment by alan2207** [comment]
@maliksenpai , thanks for this great idea! However, the purpose of this repo is not to be a template but to showcase how some things should be done, so having a CLI command for that might be an overkill and not something we need.

**Comment by maliksenpai** [comment]
I see, I offered this idea because I saw such a potential in the project, but if our goal is different, it's fine :)

**Comment by alan2207** [comment]
I really appreciate it, that would definitely be an awesome feature if this was supposed to be used as a project starter, but the plan for this repo is to serve as a showcase project for a well architectured application,  and there are already a ton of boilerplates anyway :)
