### ISSUE TITLE
Issue with Using queryClient as a Dependency of useMemo

### ISSUE THREAD

**Issue by devalirzayev** [alan2207/bulletproof-react#202]
Hi there!

queryClient has been used as a dependency of useMemo which I believe aims to prevent useless re-renders. But as far as I know, queryClient returns a class which if it is used as a dependency, it will trigger useMemo on every render.

https://github.com/alan2207/bulletproof-react/blob/ea1ebba1029a44018c2968a2f9a0fb97b2f05cf2/apps/react-vite/src/app/router.tsx#L115

Please see this article: https://profy.dev/article/react-useeffect-with-object-dependency

**Comment by alan2207** [comment]
Hey @devalirzayev, since `queryClient` reference is stable as we are not re-setting it elsewehre, and the `useMemo` hook recalculates only if the reference to queryClient change, this approach is fine and there will be no extra renders.

Thanks for sharing this though :)
