### ISSUE TITLE
[SUGGESTION] Why are the page paths hardcoded into the source code?

### ISSUE THREAD

**Issue by nyantama0616** [alan2207/bulletproof-react#218]
## The problem
In this project, the page paths are hardcoded into the source code.
[apps/nextjs-pages/src/pages/index.tsx](https://github.com/alan2207/bulletproof-react/blob/master/apps/nextjs-pages/src/pages/index.tsx)
```Typescript
if (user.data) {
  router.push('/app');
} else {
  router.push('/auth/login');
}
```

Hardcoding page paths has the following problems:
- Typos do not trigger static errors, making bugs difficult to detect.
- You have to remember the page paths.
- If the page path is changed, the all codes where it is used must also be updated.

In other words, the above code violates the DRY principle.

## Suggestion
So, my suggestion is here.
```Typescript
// Actually, you will put it in `src/utils/paths.ts`
const paths = {
  app: "/app",
  login: "/auth/login",
};

if (user.data) {
  router.push(paths.app);
} else {
  router.push(paths.login);
}
```
In some cases, the following approach might also be used.
```Typescript
const pages = {
  app: {
    path: "/app",
    title: "App",
  },
  login: {
    path: "/auth/login",
    title: "Login",
  },
};

if (user.data) {
  router.push(pages.app.path);
} else {
  router.push(pages.login.path);
}
```

I want to listen to your opinions.
Thank you.

**Comment by alan2207** [comment]
Hey @nyantama0616 , that is a very good point. I've added that in [this PR](https://github.com/alan2207/bulletproof-react/issues/218). 

Hopefully in the future, we will have more routing frameworks adopting type safe routes that [tanstack/router](https://tanstack.com/router/latest) has.
