### ISSUE TITLE
The difference between react router error-element and react error boundary

### ISSUE THREAD

**Issue by mancuoj** [alan2207/bulletproof-react#219]
I have a question about error-handling: why not use [error-element](https://reactrouter.com/en/main/route/error-element) instead of using react error boundary? When do they catch errors? Maybe it needs to be explained in the docs.

**Comment by alan2207** [comment]
Hey @mancuoj , I think it depends on where you are adding the error boundary. If it's a route level boundary, than it should be defined via react router, otherwise, if you want to handle errors on a more granular level on the page, you need to use regular error boundaries.
