### ISSUE TITLE
'Routes' is not exported from 'react-router-dom'

### ISSUE THREAD

**Issue by nizans** [alan2207/bulletproof-react#23]
Hi, 
I Was looking through the code and trying to implement some of the ideas, but I see that every Route is wrapped in a Routes component e.g: 

```
import { Route, Routes } from 'react-router-dom';

import { Discussion } from './Discussion';
import { Discussions } from './Discussions';

export const DiscussionsRoutes = () => {
  return (
    <Routes>
      <Route path="" element={<Discussions />} />
      <Route path=":discussionId" element={<Discussion />} />
    </Routes>
  );
};
```

I can't find any info about Routes in react-router docs, and also I cannot import it. I get : 

> 'Routes' is not exported from 'react-router-dom'

Is it a deprecated component? is there an alternative for it? what does it suppose to do?

Thanks!

**Comment by alan2207** [comment]
Hi,

That's because react-router v6 is being used here which introduced some API changes in comparison to v5. One of those changes is the introduction of `Routes` instead of `Switch`.

You can find more about it here:
https://reacttraining.com/blog/react-router-v6-pre/

**Comment by nizans** [comment]
Hi, 

That's what I was looking for 👍 

Thanks,
