### ISSUE TITLE
Storybook crashes. Outdated AppProvider import source.

### ISSUE THREAD

**Issue by gregarnott** [alan2207/bulletproof-react#26]
### Steps to reproduce

Standard clone repo, install, and then run storybook `yarn run storybook`.

### Error

Crashes due to missing `../src/context` in `.storybook/preview.js` (AppProvider import).
AppProvider was moved during updates to project `src/` structure.

### Fix

**File**: `.storybook/preview.js`
**Line**: 2
**Changes**:
`import { AppProvider } from '../src/providers/app';`

Documentation needs similar loving attention.
**File**: `docs/error-handling.md`
**Line**: 13
**Changes**:
`[Error Boundary Example Code](../src/providers/app.tsx)`

**Comment by alan2207** [comment]
Good catch, thanks for reporting it!
