### ISSUE TITLE
Can You provide same sturcuture for JS  ? 

### ISSUE THREAD

**Issue by marxyes** [alan2207/bulletproof-react#32]
It seems to be a bit difficult to understand this structure, can you provide or suggest any simple structure for a kick start a new project.

Or Can you publish the same structure for JS instead of TS ?

Is it necessary to put Api call inside the page (feature) folder or can we make some global service folder where we create API call?

**Comment by alan2207** [comment]
Hey, can you tell me more about what makes it difficult for you to understand the structure?

I wouldn't recommend switching to JS especially if the project is planned to grow, but if you really want it, you can just remove the TS setup and all the types and you are good to go.

About the API calls question, the reason why it is in the feature folder is that it is nice to keep it close to everything that is related to it. But yeah, you can take it outside if you want.

As mentioned in the README, you can adjust it to your needs in terms of anything.
