### ISSUE TITLE
Tailwind doesn't go well with hardhat

### ISSUE THREAD

**Issue by letteldream** [alan2207/bulletproof-react#56]
While I'm developing the NFT marketplace, I installed a hardhat.
console : npx hardhat
After developing, when I tried to compile, an error occurred.
The project doesn't recognize the tailwind module, So I reinstalled the tailwind.
console: npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
              yarn add --dev tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
Then it worked well.
However, after that, whenever I installed a new module, my project doesn't recognize tailwind and I had to reinstall tailwind everytime.
I think there is a problem with the Webpack. But I can't find the solution.
How can I handle that trouble?

**Comment by alan2207** [comment]
Hi there,

I have no experience with hardhat, but I would advise you not to use this as boilerplate/template as it uses a bit older dependencies (6 months), e.g - CRA v5 is out now which supports postcss v8 which might be compatible with your project without using compat versions of tailwind.

So I would advise you to bootstrap your project using CRA v5 or vite.js and use this repo just as a reference on how to solve different problems in your app.
