### ISSUE TITLE
Is something else needed for absolute imports to wrok?

### ISSUE THREAD

**Issue by NathanDowner** [alan2207/bulletproof-react#58]
First off thanks for this repo! It's been an incredible resource so far. I'm building a project based on its guidelines at the moment and I'm having an issue setting up the absolute imports as you described in the [absolute imports section](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-configuration.md#absolute-imports). When I run the project I get the following below error in the terminal, as well as for any other file that imports something using the `@/something` syntax. VS code correctly suggests imports using the syntax after updating the `tsconfig.json` and adding `tsconfig.paths.json` but I just want to make sure there wasn't any other config that I needed to add to get it working.

### The error
```bash
ERROR in ./src/features/auth/components/SignInPage.tsx 10:0-41
Module not found: Error: Can't resolve '@/components/Button' in '/Users/nathan/projects/react/merchant-portal/src/features/auth/components'
```

In SignInPage.tsx I've imported the Button component using
```javascript
import Button from '@/components/Button';
```

and the Button component is the default export from the file found at `./src/components/Button.tsx`.

tsconfig.paths.json
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "exclude": ["node_modules"],
  "extends": "./tsconfig.paths.json"
}
```

**Comment by alan2207** [comment]
Hey there,

You have to configure webpack alias in craco config if you haven't already:
https://github.com/alan2207/bulletproof-react/blob/8d4c3fb7a5bdb61e4557c2d3ea6eb7d6aaa817a1/craco.config.js#L4

**Comment by NathanDowner** [comment]
And if I'm not using craco, but the regular react-scripts? I'm using tailwind 3 and create-react-app v 5+

**Comment by alan2207** [comment]
You will need craco in order to override webpack configuration. I found this [repository](https://github.com/grumpyoldman-io/react-boilerplate) that includes both tailwind 3 and CRA v5 with alias configuration. It appears you do not need `tsconfig.paths.json` for CRA v5, you can define paths directly in `tsconfig.json`.

**Comment by NathanDowner** [comment]
Alright thanks !
