### ISSUE TITLE
Backend for this repo

### ISSUE THREAD

**Issue by subhamsaha-manu** [alan2207/bulletproof-react#63]
Hi thanks for this repository. Is there a back-end for this. Like I wanted to run the application locally, but cannot proceed beyond login/signup for obvious reason.

Not sure if I missed any documentation on how to achieve this.

**Comment by alan2207** [comment]
Looks like you didn't configure the `.env` file.

Here are all the steps that are required for installation:
https://github.com/alan2207/bulletproof-react/blob/master/docs/application-overview.md#get-started

The backend for this application is completely mocked with msw, therefore no additional backend stuff is required. Just make sure you have your `.env` file configured properly.

**Comment by subhamsaha-manu** [comment]
Yes.. Thank you! Had missed this part.
