### ISSUE TITLE
How can I implement bulletproof-react with MUI ?

### ISSUE THREAD

**Issue by yyykkkyyy** [alan2207/bulletproof-react#77]
Hi, I'm a very newbie to React and I'd like to refer to this wonderful template.

How can I implement this template with MUI ?

I understand this question is a very basic and general question. So I'm wondering if this is an inappropriate issue.
For instance, when I'd like to use MUI's TextField, should I change the code in the `elements/Form/` codes ?
And if so, do you have some examples ?
Definitely I don't understand some important contents about React and so on.
Sorry if this is a very off-topic question.

**Comment by alan2207** [comment]
Hi there,

As @jdnickell said, switching to another UI library should not be a problem, just make sure to follow their official guides to get everything set up. However, unless you are building a similar app to the original, I would not recommend using this repo as a boilerplate for several reasons:
- this is an example app with a limited set of build components
- you might not need everything that comes installed or you need something else (like you do with MUI)
- cleaning up what you don't need might require more work than setting everything from scratch
- some dependencies are a bit outdated (I plan to update them soon, so stay tuned :) )

I recommend that you get inspiration from this repo and the example application and start building your own application from scratch based on the project structure of the example app.

**Comment by yyykkkyyy** [comment]
@jdnickell 
Thank you for your such a kind advise! I'm a really very newbie so I didn't know how to start my app.  I read some articles that refer to wrap some components like MUI's and I believed that is a best practice.

> I'm curious if others will recommend using some kind of wrapper component for the MUI controls. For me it seems overkill, but maybe it makes writing tests easier and I suppose makes it easier for you to switch to another library later?

Yeah, I would like to know about this matter. Anyway, thank you very much !!

@alan2207 
Hi, thank you for your replying! Thanks to your reply I have my questions answered! I have learned a tremendous amount by reading this repository. There are a lot of things that I haven't know but very important.  Anyway, thank you very much and I apologize for the delay in replying.
