### ISSUE TITLE
React query v3 package needs to be upgraded to latest v4

### ISSUE THREAD

**Issue by kedarpethe37** [alan2207/bulletproof-react#99]
React query has changed to Tanstack\react-query v4 and brings lots of new APIs and improvements. Old code referring react-query needs to be updated to new API.

**Comment by sarahsga** [comment]
This repo depends on [react-query-auth](https://github.com/alan2207/react-query-auth/pull/16) which still depends on React Query v3

**Comment by diegods-ferreira** [comment]
Apperantly there is a PR for react-query-auth to migrate it to React Query v4. [This](https://github.com/alan2207/react-query-auth/pull/16) is the PR.
